spring:
  cloud:
    gcp:
      bigquery:
        dataset-name: f1_dataset
      firestore:
        project-id: f1-visualizer-488201
        database-id: f1v-db-uat
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://elysianarts-uat.us.auth0.com/
          audiences: uat.api.f1visualizer.com