spring:
  cloud:
    gcp:
      bigquery:
        dataset-name: f1_dataset
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://elysianarts.us.auth0.com/
          audiences: api.f1visualizer.com