spring:
  cloud:
    gcp:
      bigquery:
        dataset-name: f1_dataset
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-7997251.okta.com/oauth2/aus10ieis44U2jKgM698
          audiences: api.f1visualizer.com