server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-7997251.okta.com/oauth2/aus10dj3jwaXRs0xm698
          audiences: dev.api.f1visualizer.com