resource "google_redis_instance" "f1v_cache" {
  name           = "f1v-redis-${var.environment}"
  tier           = var.environment == "prod" ? "STANDARD_HA" : "BASIC"
  memory_size_gb = 1

  region             = var.region
  authorized_network = var.network_id
  connect_mode       = "DIRECT_PEERING"

  # The VPC is not a trust boundary: anything that reaches the connector subnet
  # could publish forged telemetry to every browser, or read the whole feed.
  # AUTH gives the instance a credential; SERVER_AUTHENTICATION encrypts the
  # connection so the credential and the packets are not on the wire in the
  # clear (S2).
  auth_enabled            = true
  transit_encryption_mode = "SERVER_AUTHENTICATION"

  redis_version = "REDIS_7_X"
  display_name  = "F1V Live Telemetry Cache (${var.environment})"

  labels = {
    env = var.environment
  }
}

# ==============================================================================
# AUTH STRING DELIVERY
# ==============================================================================
# The AUTH string is generated by Memorystore, so it cannot be a Terragrunt
# input. Landing it in Secret Manager lets Cloud Run mount it as
# SPRING_DATA_REDIS_PASSWORD without it passing through a service's env_vars
# map, where it would be readable from the revision description.
resource "google_secret_manager_secret" "redis_auth" {
  secret_id = "f1v-redis-auth-${var.environment}"
  project   = var.project_id

  replication {
    auto {}
  }

  labels = {
    env = var.environment
  }
}

resource "google_secret_manager_secret_version" "redis_auth" {
  secret      = google_secret_manager_secret.redis_auth.id
  secret_data = google_redis_instance.f1v_cache.auth_string
}
