resource "google_redis_instance" "f1v_cache" {
  name           = "f1v-redis-${var.environment}"
  tier           = var.tier
  memory_size_gb = var.memory_size_gb

  region             = var.region
  authorized_network = var.network_id
  connect_mode       = "DIRECT_PEERING"

  # The VPC is not a trust boundary: anything that reaches the connector subnet
  # could publish forged telemetry to every browser, or read the whole feed.
  # AUTH gives the instance a credential; SERVER_AUTHENTICATION encrypts the
  # connection so the credential and the packets are not on the wire in the
  # clear (S2).
  auth_enabled            = true
  transit_encryption_mode = "SERVER_AUTHENTICATION"

  redis_version = "REDIS_7_X"
  display_name  = "F1V Live Telemetry Cache (${var.environment})"

  labels = {
    env = var.environment
  }
}

# ==============================================================================
# AUTH STRING DELIVERY
# ==============================================================================
# The AUTH string is generated by Memorystore, so it cannot be a Terragrunt
# input. Landing it in Secret Manager lets Cloud Run mount it as
# SPRING_DATA_REDIS_PASSWORD without it passing through a service's env_vars
# map, where it would be readable from the revision description.
resource "google_secret_manager_secret" "redis_auth" {
  secret_id = "f1v-redis-auth-${var.environment}"
  project   = var.project_id

  replication {
    auto {}
  }

  labels = {
    env = var.environment
  }
}

resource "google_secret_manager_secret_version" "redis_auth" {
  secret      = google_secret_manager_secret.redis_auth.id
  secret_data = google_redis_instance.f1v_cache.auth_string
}

# SEC-3: roles/secretmanager.secretAccessor was a project-level binding, so every
# environment's runtime identity could read every other environment's Redis
# credential — sa-f1v-data-ingestion-dev could read f1v-redis-auth-prod. This
# secret is granted to the accounts of the three services that connect to this
# instance, and to nothing else.
resource "google_secret_manager_secret_iam_member" "auth_accessors" {
  for_each = toset(var.auth_secret_accessors)

  project   = var.project_id
  secret_id = google_secret_manager_secret.redis_auth.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = each.value
}
