include "root" {
  path = find_in_parent_folders("root.hcl")
}

# REL-8: a unit rename, a module path change or a stray `run --all destroy` all
# plan a destroy without a prompt. Terragrunt refuses to run one here at all;
# removing this line is the deliberate act that a production teardown should be.
prevent_destroy = true

terraform {
  source = "../../../modules/cloud-run-backend"
}

dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_data_ingestion_email = "sa-f1v-data-ingestion-prod@f1v-example-project.iam.gserviceaccount.com"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    vpc_access_connector_id = "projects/f1v-example-project/locations/us-central1/connectors/f1v-vpc-prod-conn-MOCK"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "secrets" {
  config_path = "../secrets"
  mock_outputs = {
    openf1_username_secret_id = "f1v-api-openf1-login-user-email"
    openf1_password_secret_id = "f1v-api-openf1-login-user-password"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  project_id   = "f1v-example-project"
  region       = "us-central1"
  service_name = "f1v-service-data-ingestion-prod"
  service_account_email = dependency.iam.outputs.sa_data_ingestion_email

  # O3: prod inherited the module's DEV/UAT default of false.
  deletion_protection = true
  image_url    = "us-central1-docker.pkg.dev/f1v-example-project/f1v-repo/data-ingestion:latest-prod"

  # CPLX-1: reached through the API load balancer's serverless NEG, which
  # cannot present an ID token — so the invoker binding is allUsers and the
  # *.run.app URL is closed off with ingress instead. This is the arrangement
  # telemetry has used since it started bypassing the gateway for WebSockets.
  # The service still validates the Auth0 JWT itself, which is now the only
  # place that happens rather than the second.
  is_public = true
  ingress   = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"

  # P4: a load is minutes of OpenF1 calls and BigQuery writes, and the replay
  # tick needs CPU on the same pinned instance. Sized for that, not for a
  # request-per-core REST service.
  container_concurrency = 20

  # Always-on: eliminates cold starts for ingestion commands and reference data loading
  min_instance_count = 1

  # R1: the stateful half — the replay engine, its prefetcher and the MQTT
  # bridge — moved to f1v-service-replay-worker. What is left is stateless HTTP:
  # loaders, job status, and commands published to a Redis stream. It scales.

  # Batch BigQuery loads still want headroom; the replay buffers no longer live here.
  cpu    = "1000m"
  memory = "1024Mi"

  # Needs VPC access to write to Redis
  vpc_connector_id = dependency.networking.outputs.vpc_access_connector_id

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = "prod"

    # R3: ingestion job status
    "SPRING_CLOUD_GCP_FIRESTORE_PROJECT_ID"  = "f1v-example-project"
    "SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID" = "f1v-db-prod"

    # --- NEW: Explicitly inject Security Properties ---
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = "https://elysianarts.us.auth0.com/"
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = "api.f1visualizer.com"
  }

  # The Memorystore AUTH string is generated by GCP, so it is mounted from
  # Secret Manager rather than passed through env_vars (S2).
  secret_env_vars = {
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }

    # S6: read by Cloud Run at deploy time instead of by a hand-rolled Secret
    # Manager client at startup, which pinned nothing and pulled the client,
    # protobuf and gRPC stack into every ingestion image.
    # SEC-6: the secret ids come from the unit that declares the containers, so a
    # rename cannot leave a service pointing at a secret that no longer exists.
    #
    # `version` is stated rather than left to the module's "latest" default. It
    # is still "latest" today, because the current version numbers are live state
    # this repository does not know — but changing it is now a one-line reviewed
    # diff rather than an edit to a default nobody sees.
    "F1V_OPENF1_USERNAME" = {
      secret  = dependency.secrets.outputs.openf1_username_secret_id
      version = "latest"
    }
    "F1V_OPENF1_PASSWORD" = {
      secret  = dependency.secrets.outputs.openf1_password_secret_id
      version = "latest"
    }
  }
}
