spring:
  cloud:
    gcp:
      bigquery:
        dataset-name: f1_dataset
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      timeout: 10000ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-7997251.okta.com/oauth2/aus10ie9658X0CXQp698
          audiences: uat.api.f1visualizer.com