spring:
  cloud:
    gcp:
      bigquery:
        dataset-name: f1_dataset
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 10000ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://elysianarts-uat.us.auth0.com/
          audiences: uat.api.f1visualizer.com