include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "../../../modules/cloud-run-backend"
}

dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_data_ingestion_email = "sa-f1v-data-ingestion-dev@f1-visualizer-488201.iam.gserviceaccount.com"
  }
}

dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    vpc_access_connector_id = "projects/f1-visualizer-488201/locations/us-central1/connectors/f1v-vpc-dev-conn-MOCK"
  }
}

dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
  }
}

inputs = {
  project_id   = "f1-visualizer-488201"
  region       = "us-central1"
  service_name = "f1v-service-data-ingestion-dev"
  service_account_email = dependency.iam.outputs.sa_data_ingestion_email
  image_url    = "us-central1-docker.pkg.dev/f1-visualizer-488201/f1v-repo/data-ingestion:latest-dev"

  # CPLX-1: reached through the API load balancer's serverless NEG, which
  # cannot present an ID token — so the invoker binding is allUsers and the
  # *.run.app URL is closed off with ingress instead. This is the arrangement
  # telemetry has used since it started bypassing the gateway for WebSockets.
  # The service still validates the Auth0 JWT itself, which is now the only
  # place that happens rather than the second.
  is_public = true
  ingress   = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"

  # Always-on: eliminates cold starts for ingestion commands and reference data loading
  min_instance_count = 1

  # P4: a load is minutes of OpenF1 calls and BigQuery writes, and the replay
  # tick needs CPU on the same pinned instance. Sized for that, not for a
  # request-per-core REST service.
  container_concurrency = 20

  # R1: the stateful half — the replay engine, its prefetcher and the MQTT
  # bridge — moved to f1v-service-replay-worker. What is left is stateless HTTP:
  # loaders, job status, and commands published to a Redis stream. It scales.

  # Batch BigQuery loads still want headroom; the replay buffers no longer live here.
  cpu    = "1000m"
  memory = "1024Mi"

  # Needs VPC access to write to Redis
  vpc_connector_id = dependency.networking.outputs.vpc_access_connector_id

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = "dev"

    # R3: ingestion job status
    "SPRING_CLOUD_GCP_FIRESTORE_PROJECT_ID"  = "f1-visualizer-488201"
    "SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID" = "f1v-db-dev"

    # --- NEW: Explicitly inject Security Properties ---
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = "https://elysianarts-dev.us.auth0.com/"
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = "dev.api.f1visualizer.com"
  }

  # The Memorystore AUTH string is generated by GCP, so it is mounted from
  # Secret Manager rather than passed through env_vars (S2).
  secret_env_vars = {
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }

    # S6: read by Cloud Run at deploy time instead of by a hand-rolled Secret
    # Manager client at startup, which pinned nothing and pulled the client,
    # protobuf and gRPC stack into every ingestion image.
    #
    # TODO: pin `version` to the current secret version once it is known; until
    # then these track "latest", which is the behaviour being replaced.
    "F1V_OPENF1_USERNAME" = { secret = "f1v-api-openf1-login-user-email" }
    "F1V_OPENF1_PASSWORD" = { secret = "f1v-api-openf1-login-user-password" }
  }
}
