# ==============================================================================
# f1v-service-data-ingestion — OpenF1 loaders and ingestion commands
# ==============================================================================
# CPLX-3: the shared definition. Everything here was repeated in three
# near-identical unit files; what differs per environment comes from env.hcl, and
# a unit adds only a genuine override.

locals {
  env  = read_terragrunt_config(find_in_parent_folders("env.hcl")).locals
  root = dirname(find_in_parent_folders("root.hcl"))
}

terraform {
  source = "${local.root}/modules/cloud-run"
}

dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_data_ingestion_email = "sa-f1v-data-ingestion-${local.env.environment}@${local.env.project_id}.iam.gserviceaccount.com"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    network_name    = local.env.network_name
    subnetwork_name = "${local.env.network_name}-subnet"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
    redis_ca_secret_id   = "f1v-redis-ca-MOCK"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "bigquery" {
  config_path = "../bigquery"
  mock_outputs = {
    dataset_id = local.env.bigquery_dataset_id
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  region       = local.env.region
  service_name = "f1v-service-data-ingestion-${local.env.environment}"
  image_url    = "${local.env.registry_host}/${local.env.repository}/data-ingestion:${local.env.image_tag}"

  service_account_email = dependency.iam.outputs.sa_data_ingestion_email

  # CPLX-1: reached through the API load balancer's serverless NEG, which cannot
  # present an ID token — so the invoker binding is allUsers and the *.run.app URL
  # is closed off with ingress instead. The service validates the Auth0 JWT
  # itself, which is now the only place that happens rather than the second.
  invokers = ["allUsers"]
  ingress  = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"

  # Always-on: eliminates cold starts for ingestion commands and reference loads.
  min_instance_count = local.env.rest_min_instances

  # P4: a load is minutes of OpenF1 calls and BigQuery writes. Sized for that,
  # not for a request-per-core REST service.
  container_concurrency = 20

  # R1: the stateful half — the replay engine, its prefetcher and the MQTT bridge
  # — moved to f1v-service-replay-worker. What is left is stateless HTTP:
  # loaders, job status, and commands published to a Redis stream. It scales.
  cpu    = "1000m"
  memory = "1024Mi"

  vpc_network    = dependency.networking.outputs.network_name
  vpc_subnetwork = dependency.networking.outputs.subnetwork_name

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = local.env.environment

    "F1V_BIGQUERY_DATASET" = dependency.bigquery.outputs.dataset_id

    # R3: ingestion job status lives in Firestore so it survives the deploy that
    # restarts the service mid-load.
    "SPRING_CLOUD_GCP_FIRESTORE_PROJECT_ID"  = local.env.project_id
    "SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID" = local.env.firestore_database_id

    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = local.env.auth0_issuer
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = local.env.auth0_audience
  }

  secret_env_vars = {
    # S2: generated by GCP, so it is mounted from Secret Manager rather than
    # passed through env_vars where it would be readable from the revision.
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }

    # REL-3: the per-instance CA chain Memorystore signs its certificate with.
    # Both track "latest" because both are values GCP rotates for us.
    "F1V_REDIS_CA_CERT" = { secret = dependency.redis.outputs.redis_ca_secret_id }

    # SEC-6: one credential for all three environments, because OpenF1 issues one
    # account. Declared and granted in infrastructure/platform, and named by id
    # rather than read from a dependency — depending across the layer boundary
    # would pull the platform unit into an environment's `run --all`.
    "F1V_OPENF1_USERNAME" = {
      secret  = "f1v-api-openf1-login-user-email"
      version = "latest"
    }
    "F1V_OPENF1_PASSWORD" = {
      secret  = "f1v-api-openf1-login-user-password"
      version = "latest"
    }
  }
}
