# ==============================================================================
# f1v-service-replay-worker — the stateful replay singleton
# ==============================================================================
# CPLX-3: the shared definition. Everything here was repeated in three
# near-identical unit files; what differs per environment comes from env.hcl, and
# a unit adds only a genuine override.

locals {
  env  = read_terragrunt_config(find_in_parent_folders("env.hcl")).locals
  root = dirname(find_in_parent_folders("root.hcl"))
}

terraform {
  source = "${local.root}/modules/cloud-run"
}

dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_replay_worker_email = "sa-f1v-replay-worker-${local.env.environment}@${local.env.project_id}.iam.gserviceaccount.com"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    network_name    = local.env.network_name
    subnetwork_name = "${local.env.network_name}-subnet"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
    redis_ca_secret_id   = "f1v-redis-ca-MOCK"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "bigquery" {
  config_path = "../bigquery"
  mock_outputs = {
    dataset_id = local.env.bigquery_dataset_id
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  region       = local.env.region
  service_name = "f1v-service-replay-worker-${local.env.environment}"
  image_url    = "${local.env.registry_host}/${local.env.repository}/replay-worker:${local.env.image_tag}"

  service_account_email = dependency.iam.outputs.sa_replay_worker_email

  # R1: the replay engine, its chunk prefetcher and the MQTT bridge are stateful
  # singletons. They used to share a deployment with the stateless HTTP loaders,
  # where Cloud Run's default of five instances meant a play, pause or seek could
  # land on an instance that was not running the replay — and a scale-down threw
  # the replay away.
  #
  # No callers at all: commands arrive on a Redis stream and state goes back to
  # Redis, so nothing outside the platform's own health probes reaches it.
  invokers = []
  ingress  = "INGRESS_TRAFFIC_INTERNAL_ONLY"

  # Exactly one. This is the whole point of the service.
  min_instance_count = local.env.worker_enabled ? 1 : 0
  max_instance_count = 1

  # The 250 ms tick, the chunk prefetch executor and the MQTT callbacks all run
  # between requests — and there are no requests here at all.
  cpu_idle = false

  # 100k-object replay buffers, BigQuery reads and MQTT + Redis I/O.
  cpu    = "2000m"
  memory = "1024Mi"

  # Redis is the command channel, the state store and the packet destination.
  vpc_network    = dependency.networking.outputs.network_name
  vpc_subnetwork = dependency.networking.outputs.subnetwork_name

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = local.env.environment

    "F1V_BIGQUERY_DATASET" = dependency.bigquery.outputs.dataset_id

    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = local.env.auth0_issuer
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = local.env.auth0_audience
  }

  secret_env_vars = {
    # S2: generated by GCP, so it is mounted from Secret Manager rather than
    # passed through env_vars where it would be readable from the revision.
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }

    # REL-3: the per-instance CA chain Memorystore signs its certificate with.
    # Both track "latest" because both are values GCP rotates for us.
    "F1V_REDIS_CA_CERT" = { secret = dependency.redis.outputs.redis_ca_secret_id }

    # SEC-6: one credential for all three environments, because OpenF1 issues one
    # account. Declared and granted in infrastructure/platform, and named by id
    # rather than read from a dependency — depending across the layer boundary
    # would pull the platform unit into an environment's `run --all`.
    "F1V_OPENF1_USERNAME" = {
      secret  = "f1v-api-openf1-login-user-email"
      version = "latest"
    }
    "F1V_OPENF1_PASSWORD" = {
      secret  = "f1v-api-openf1-login-user-password"
      version = "latest"
    }
  }
}
