# ==============================================================================
# f1v-service-telemetry — Redis pub/sub to WebSocket broadcast
# ==============================================================================
# CPLX-3: the shared definition. Everything here was repeated in three
# near-identical unit files; what differs per environment comes from env.hcl, and
# a unit adds only a genuine override.

locals {
  env  = read_terragrunt_config(find_in_parent_folders("env.hcl")).locals
  root = dirname(find_in_parent_folders("root.hcl"))
}

terraform {
  source = "${local.root}/modules/cloud-run"
}

dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_telemetry_email = "sa-f1v-telemetry-${local.env.environment}@${local.env.project_id}.iam.gserviceaccount.com"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    network_name    = local.env.network_name
    subnetwork_name = "${local.env.network_name}-subnet"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
    redis_ca_secret_id   = "f1v-redis-ca-MOCK"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  region       = local.env.region
  service_name = "f1v-service-telemetry-${local.env.environment}"
  image_url    = "${local.env.registry_host}/${local.env.repository}/telemetry:${local.env.image_tag}"

  service_account_email = dependency.iam.outputs.sa_telemetry_email

  # S3: fronted by the load balancer's serverless NEG, which cannot present an ID
  # token — so the public invoker binding stays and ingress is narrowed instead.
  invokers = ["allUsers"]
  ingress  = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"

  # High-frequency Redis pub/sub to WebSocket broadcast: 1000+ msg/sec during a
  # live session.
  cpu    = "2000m"
  memory = "1024Mi"

  # WebSocket connections are long-lived. An hour is a full race replay without
  # the connection being terminated under it.
  timeout = "3600s"

  # A cold-starting backend causes transient connection failures, and the
  # frontend opens its STOMP connection immediately after login — so this is a
  # per-environment decision (PERF-4) rather than a constant.
  min_instance_count = local.env.telemetry_warm ? 1 : 0

  # The Redis pub/sub subscriber delivers on its own thread. With CPU allocated
  # only during requests, a session with no inbound HTTP traffic stalls the
  # re-broadcast to every connected browser (R1).
  cpu_idle = false

  # Long-lived and mostly idle, so this is really "connections per instance".
  # 1000 on one SimpleBroker was optimistic; 250 lets Cloud Run scale out, and
  # every instance receives the same Redis messages, so scaling out is correct
  # rather than merely tolerable (P4).
  container_concurrency = 250

  vpc_network    = dependency.networking.outputs.network_name
  vpc_subnetwork = dependency.networking.outputs.subnetwork_name

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = local.env.environment

    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = local.env.auth0_issuer
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = local.env.auth0_audience
  }

  secret_env_vars = {
    # S2: generated by GCP, so it is mounted from Secret Manager rather than
    # passed through env_vars where it would be readable from the revision.
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }

    # REL-3: the per-instance CA chain Memorystore signs its certificate with.
    # Both track "latest" because both are values GCP rotates for us.
    "F1V_REDIS_CA_CERT" = { secret = dependency.redis.outputs.redis_ca_secret_id }
  }
}
