swagger: '2.0'
info:
  title: F1 Visualizer API
  description: The central API Gateway routing traffic to F1V microservices.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  okta_jwt:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://integrator-7997251.okta.com/oauth2/default"
    x-google-jwks_uri: "https://integrator-7997251.okta.com/oauth2/default/v1/keys"
    x-google-audiences: "api.f1visualizer.com"
paths:
  /api/v1/analysis/session/{sessionKey}/laps:
    get:
      summary: Get historical lap times
      operationId: getSessionLaps
      parameters:
        - name: sessionKey
          in: path
          required: true
          type: integer
      x-google-backend:
        address: DATA_ANALYSIS_SERVICE_URL_PLACEHOLDER
        deadline: 15.0
      responses:
        '200':
          description: A list of lap records
          schema:
            type: array
            items:
              type: object
        '401':
          description: Unauthorized
      security:
        - okta_jwt: []
  /api/v1/users/me:
    get:
      summary: Get current user profile
      operationId: getCurrentUser
      x-google-backend:
        address: USER_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: User profile
      security:
        - okta_jwt: []
    options:
      operationId: corsUsers
      x-google-backend:
        address: USER_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '204':
          description: No Content
  /api/v1/debug/publish:
    post:
      summary: Manually inject telemetry packet
      operationId: publishDebugTelemetry
      x-google-backend:
        address: TELEMETRY_SERVICE_URL_PLACEHOLDER
      responses:
        '200':
          description: Packet published
      security:
        - okta_jwt: []