swagger: '2.0'
info:
  title: F1 Visualizer API
  description: The central API Gateway routing traffic to F1V microservices.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  okta_jwt:
    authorizationUrl: "OKTA_ISSUER_URI_PLACEHOLDER/v1/authorize"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "OKTA_ISSUER_URI_PLACEHOLDER"
    x-google-jwks_uri: "OKTA_ISSUER_URI_PLACEHOLDER/v1/keys"
    x-google-audiences: "OKTA_AUDIENCE_PLACEHOLDER"
paths:
  /v1/telemetry/**:
    get:
      summary: Proxy for Telemetry Service
      operationId: telemetryProxy
      x-google-backend:
        address: TELEMETRY_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      security:
        - okta_jwt: []
    options:
      summary: CORS support
      operationId: telemetryOptions
      x-google-backend:
        address: TELEMETRY_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
  /v1/analysis/**:
    get:
      summary: Proxy for Analysis Service
      operationId: analysisProxy
      x-google-backend:
        address: DATA_ANALYSIS_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      security:
        - okta_jwt: []
    options:
      summary: CORS support
      operationId: analysisOptions
      x-google-backend:
        address: DATA_ANALYSIS_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
  /v1/user/**:
    get:
      summary: Proxy for User Service (Read)
      operationId: userProxy
      x-google-backend:
        address: USER_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      security:
        - okta_jwt: []
    post:
      summary: Proxy for User Service (Write)
      operationId: userCreateProxy
      x-google-backend:
        address: USER_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      security:
        - okta_jwt: []
    options:
      summary: CORS support
      operationId: userOptions
      x-google-backend:
        address: USER_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
  /v1/ingestion/**:
    post:
      summary: Proxy for Data Ingestion Service (Commands)
      operationId: ingestionCommandProxy
      x-google-backend:
        address: DATA_INGESTION_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      security:
        - okta_jwt: [ ]
    options:
      summary: CORS support
      operationId: ingestionOptions
      x-google-backend:
        address: DATA_INGESTION_SERVICE_URL_PLACEHOLDER
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK