spring:
  cloud:
    gcp:
      firestore:
        project-id: f1-visualizer-488201
        database-id: f1v-db-dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://elysianarts-dev.us.auth0.com/
          audiences: dev.api.f1visualizer.com