spring:
  cloud:
    gcp:
      firestore:
        project-id: f1-visualizer-488201
        database-id: f1v-db-uat
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-7997251.okta.com/oauth2/aus10ie9658X0CXQp698
          audiences: uat.api.f1visualizer.com