spring:
  cloud:
    gcp:
      firestore:
        project-id: f1v-example-project
        database-id: f1-visualizer-db-dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://example-okta-org.okta.com/oauth2/default