server:
  port: 8083
spring:
  cloud:
    gcp:
      firestore:
        project-id: f1-visualizer-488201
        database-id: (default)
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://elysianarts-dev.us.auth0.com/.well-known/jwks.json
          audiences: dev.api.f1visualizer.com