server:
  port: 8083
spring:
  cloud:
    gcp:
      firestore:
        project-id: f1v-example-project
        database-id: (default)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://example-tenant.us.auth0.com/
          audiences: dev.api.f1visualizer.com