include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "../../../modules/cloud-run-backend"
}

# 1. Dependency on IAM module
dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_telemetry_email = "sa-f1v-telemetry-prod@f1-visualizer-488201.iam.gserviceaccount.com"
  }
}

# 2. Dependency on Networking (For VPC Access Connector)
dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    vpc_access_connector_id = "projects/f1-visualizer-488201/locations/us-central1/connectors/f1v-vpc-prod-conn-MOCK"
  }
}

# 3. Dependency on Redis (For Host/Port Environment Variables)
dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
  }
}

inputs = {
  project_id   = "f1-visualizer-488201"
  region       = "us-central1"
  service_name = "f1v-service-telemetry-prod"
  service_account_email = dependency.iam.outputs.sa_telemetry_email

  # O3: prod inherited the module's DEV/UAT default of false.
  deletion_protection = true

  # S3: fronted by the load balancer's serverless NEG, which cannot present an ID
  # token — so the public invoker binding stays and ingress is narrowed instead,
  # keeping the *.run.app URL from answering the internet directly.
  is_public = true
  ingress   = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"

  # Pointing to the Artifact Registry repo we created
  image_url    = "us-central1-docker.pkg.dev/f1-visualizer-488201/f1v-repo/telemetry:latest"

  # Elevated resources: high-frequency Redis Pub/Sub to WebSocket broadcast (1000+ msg/sec during live sessions)
  cpu    = "2000m"
  memory = "1024Mi"

  # WebSocket / SockJS connections are long-lived. 3600s (1h) gives ample
  # headroom for a full race replay without the connection being terminated.
  timeout = "3600s"

  # Keep 1 instance warm to eliminate cold-start delays on WebSocket connections.
  # The frontend establishes a STOMP/SockJS connection immediately after login;
  # a cold-starting backend causes transient connection failures.
  min_instance_count = 1

  # The Redis pub/sub subscriber delivers on its own thread. With CPU allocated
  # only during requests, a session with no inbound HTTP traffic stalls the
  # re-broadcast to every connected browser (R1).
  cpu_idle = false

  # WebSocket sessions are long-lived and mostly idle, so concurrency here is
  # really "connections per instance". 1000 on one SimpleBroker was optimistic;
  # 250 lets Cloud Run scale out instead, and every instance receives the same
  # Redis messages, so scaling out is correct rather than merely tolerable (P4).
  container_concurrency = 250
  vpc_connector_id      = dependency.networking.outputs.vpc_access_connector_id

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = "prod"

    # --- NEW: Explicitly inject Security Properties ---
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = "https://elysianarts.us.auth0.com/"
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = "api.f1visualizer.com"
  }

  # The Memorystore AUTH string is generated by GCP, so it is mounted from
  # Secret Manager rather than passed through env_vars (S2).
  secret_env_vars = {
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }
  }
}
