include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "../../../modules/cloud-run"
}

dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_data_ingestion_email = "sa-f1v-data-ingestion-uat@f1-visualizer-488201.iam.gserviceaccount.com"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    network_name    = "f1v-vpc-uat"
    subnetwork_name = "f1v-vpc-uat-subnet"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}


dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
    redis_ca_secret_id   = "f1v-redis-ca-MOCK"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "bigquery" {
  config_path = "../bigquery"
  mock_outputs = {
    dataset_id = "f1_dataset_uat"
  }

  # REL-7: mocks are for planning, never for applying.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  project_id   = "f1-visualizer-488201"
  region       = "us-east1"
  service_name = "f1v-service-data-ingestion-uat"
  service_account_email = dependency.iam.outputs.sa_data_ingestion_email
  image_url    = "us-east1-docker.pkg.dev/f1-visualizer-488201/f1v-repo/data-ingestion:latest-uat"

  # CPLX-1: reached through the API load balancer's serverless NEG, which
  # cannot present an ID token — so the invoker binding is allUsers and the
  # *.run.app URL is closed off with ingress instead. This is the arrangement
  # telemetry has used since it started bypassing the gateway for WebSockets.
  # The service still validates the Auth0 JWT itself, which is now the only
  # place that happens rather than the second.
  invokers = ["allUsers"]
  ingress  = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"

  # Always-on: eliminates cold starts for ingestion commands and reference data loading
  min_instance_count = 1

  # P4: a load is minutes of OpenF1 calls and BigQuery writes, and the replay
  # tick needs CPU on the same pinned instance. Sized for that, not for a
  # request-per-core REST service.
  container_concurrency = 20

  # R1: the stateful half — the replay engine, its prefetcher and the MQTT
  # bridge — moved to f1v-service-replay-worker. What is left is stateless HTTP:
  # loaders, job status, and commands published to a Redis stream. It scales.

  # Batch BigQuery loads still want headroom; the replay buffers no longer live here.
  cpu    = "1000m"
  memory = "1024Mi"

  # Needs VPC access to write to Redis
  vpc_network    = dependency.networking.outputs.network_name
  vpc_subnetwork = dependency.networking.outputs.subnetwork_name

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = "uat"

    # CPLX-2: the backend has read this since C4 and nothing ever set it, so
    # every environment fell through to the shared "f1_dataset".
    "F1V_BIGQUERY_DATASET" = dependency.bigquery.outputs.dataset_id

    # R3: ingestion job status
    "SPRING_CLOUD_GCP_FIRESTORE_PROJECT_ID"  = "f1-visualizer-488201"
    "SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID" = "f1v-db-uat"

    # --- NEW: Explicitly inject Security Properties ---
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = "https://elysianarts-uat.us.auth0.com/"
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = "uat.api.f1visualizer.com"
  }

  # The Memorystore AUTH string is generated by GCP, so it is mounted from
  # Secret Manager rather than passed through env_vars (S2).
  secret_env_vars = {
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }

    # REL-3: the per-instance CA chain Memorystore signs its certificate with.
    # Tracked at "latest" like the AUTH string, because both are values GCP
    # rotates for us rather than values a deploy should decide.
    "F1V_REDIS_CA_CERT" = { secret = dependency.redis.outputs.redis_ca_secret_id }

    # S6: read by Cloud Run at deploy time instead of by a hand-rolled Secret
    # Manager client at startup, which pinned nothing and pulled the client,
    # protobuf and gRPC stack into every ingestion image.
    # SEC-6: one credential for all three environments, because OpenF1 issues
    # one account. Declared and granted in infrastructure/platform, and named
    # here by id rather than read from a dependency — depending across the layer
    # boundary would pull the platform unit into an environment's `run --all`,
    # which is the coupling CPLX-2 removes.
    #
    # `version` is stated rather than left to the module's "latest" default. It
    # is still "latest" today, because the current version numbers are live state
    # this repository does not know — but changing it is a one-line reviewed diff
    # rather than an edit to a default nobody sees.
    "F1V_OPENF1_USERNAME" = {
      secret  = "f1v-api-openf1-login-user-email"
      version = "latest"
    }
    "F1V_OPENF1_PASSWORD" = {
      secret  = "f1v-api-openf1-login-user-password"
      version = "latest"
    }
  }
}
