include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "../../../modules/cloud-run-backend"
}

dependency "iam" {
  config_path = "../iam-and-secrets"
  mock_outputs = {
    sa_data_ingestion_email = "sa-f1v-data-ingestion-uat@f1v-example-project.iam.gserviceaccount.com"
    sa_gateway_email = "sa-f1v-gateway-uat@f1v-example-project.iam.gserviceaccount.com"
  }
}

dependency "networking" {
  config_path = "../networking"
  mock_outputs = {
    vpc_access_connector_id = "projects/f1v-example-project/locations/us-east1/connectors/f1v-vpc-uat-conn-MOCK"
  }
}

dependency "redis" {
  config_path = "../redis"
  mock_outputs = {
    redis_host           = "10.0.0.5"
    redis_port           = 6379
    redis_auth_secret_id = "f1v-redis-auth-MOCK"
  }
}

inputs = {
  project_id   = "f1v-example-project"
  region       = "us-east1"
  service_name = "f1v-service-data-ingestion-uat"
  service_account_email = dependency.iam.outputs.sa_data_ingestion_email
  image_url    = "us-east1-docker.pkg.dev/f1v-example-project/f1v-repo/data-ingestion:latest-uat"

  # S3: the *.run.app URL no longer answers the internet. Only the API Gateway's
  # service account can invoke this service, and it presents an ID token minted
  # for the service's own URL. In-app JWT validation stays, as defence in depth.
  is_public                = false
  invoker_service_accounts = [dependency.iam.outputs.sa_gateway_email]

  # Always-on: eliminates cold starts for ingestion commands and reference data loading
  min_instance_count = 1

  # P4: a load is minutes of OpenF1 calls and BigQuery writes, and the replay
  # tick needs CPU on the same pinned instance. Sized for that, not for a
  # request-per-core REST service.
  container_concurrency = 20

  # R1: the stateful half — the replay engine, its prefetcher and the MQTT
  # bridge — moved to f1v-service-replay-worker. What is left is stateless HTTP:
  # loaders, job status, and commands published to a Redis stream. It scales.

  # Batch BigQuery loads still want headroom; the replay buffers no longer live here.
  cpu    = "1000m"
  memory = "1024Mi"

  # Needs VPC access to write to Redis
  vpc_connector_id = dependency.networking.outputs.vpc_access_connector_id

  env_vars = {
    "SPRING_DATA_REDIS_HOST" = dependency.redis.outputs.redis_host
    "SPRING_DATA_REDIS_PORT" = dependency.redis.outputs.redis_port
    "SPRING_PROFILES_ACTIVE" = "uat"

    # R3: ingestion job status
    "SPRING_CLOUD_GCP_FIRESTORE_PROJECT_ID"  = "f1v-example-project"
    "SPRING_CLOUD_GCP_FIRESTORE_DATABASE_ID" = "f1v-db-uat"

    # --- NEW: Explicitly inject Security Properties ---
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI" = "https://elysianarts-uat.us.auth0.com/"
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES"  = "uat.api.f1visualizer.com"
  }

  # The Memorystore AUTH string is generated by GCP, so it is mounted from
  # Secret Manager rather than passed through env_vars (S2).
  secret_env_vars = {
    "SPRING_DATA_REDIS_PASSWORD" = { secret = dependency.redis.outputs.redis_auth_secret_id }

    # S6: read by Cloud Run at deploy time instead of by a hand-rolled Secret
    # Manager client at startup, which pinned nothing and pulled the client,
    # protobuf and gRPC stack into every ingestion image.
    #
    # TODO: pin `version` to the current secret version once it is known; until
    # then these track "latest", which is the behaviour being replaced.
    "F1V_OPENF1_USERNAME" = { secret = "f1v-api-openf1-login-user-email" }
    "F1V_OPENF1_PASSWORD" = { secret = "f1v-api-openf1-login-user-password" }
  }
}
